### PR TITLE
fix #237 Don't open wrong local document from ObjectScript Explorer

### LINKED ISSUE #237: ObjectScript Explorer's view of another namespace incorrectly opens a local file if the name matches
1. Set up a single-root workspace with an `objectscript.conn` that connects to namespace A on a server, in which there is a routine named Test1.int
2. Use ObjectScript Explorer (OE), expand the Routines folder and export Test1.int to the local workspace folder.
3. In namespace B on the same server, create a Test1.int routine that isn't the same as the one in A.
4. Use OE to "View Another Namespace", and pick B.
5. Expand the Routines folder of B, find Test1.int and click on it to open the file.
6. 🐛 The local copy of Test1.int (exported from A) opens. It should have opened the server-side copy from namespace B.

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This fixes #237.

It also adds visual differentiation between files in OE that will open from the server and those that will open from the local workspace.

image

Problem indicators will display for the latter.

### CODE REVIEW

File: src/explorer/models/cspFileNode.ts [hunk 1]
```diff
@@ -10,16 +10,19 @@ export class CSPFileNode extends NodeBase {
...
 
     return {
       collapsibleState: vscode.TreeItemCollapsibleState.None,
       command: {
-        arguments: [DocumentContentProvider.getUri(this.fullName, this.workspaceFolder, this.namespace)],
+        arguments: [itemUri],
         command: "vscode-objectscript.explorer.openCSPFile",
         title: "Open File",
       },
       contextValue: CSPFileNode.contextValue,
```
Comment (daimor) [inline src/explorer/models/cspFileNode.ts:23]: resourceUri missed?

File: src/explorer/models/workspaceNode.ts [hunk 2]
```diff
@@ -33,19 +33,59 @@ export class WorkspaceNode extends NodeBase {
...
 
-    node = new RootNode("Routines", "", "dataRootNode:routinesRootNode", "RTN", this.options);
+    node = new RootNode(
+      "Routines",
+      "",
+      "dataRootNode:routinesRootNode",
+      "RTN",
+      this.options,
+      false
+      //new vscode.ThemeIcon("note")
```
Comment (daimor) [inline src/explorer/models/workspaceNode.ts:54]: Why commented?

Comment (gjsjohnmurray) [reply src/explorer/models/workspaceNode.ts:54]: Because at the moment there seems to be a tree bug which messes up alignment if some items (i.e. local files) have icons and others (remote) don't. I only see this bug when the containing folder has an icon.

I plan to report this on the VSCode project. Assuming it gets fixed we can uncomment the lines that add icons to our folders.

File: src/explorer/models/cspFileNode.ts (hunk 1 above)
Comment (gjsjohnmurray) [reply src/explorer/models/cspFileNode.ts:23]: I don't understand what you mean.

Comment (daimor) [reply src/explorer/models/cspFileNode.ts:23]: any other node class has `resourceUri` field here as well.
```suggestion
      resourceUri: isLocalFile ? itemUri : undefined,
      contextValue: CSPFileNode.contextValue,
```
