### PR TITLE
Fix import of binary files such as webapp images (#1060)

### LINKED ISSUE #1060: Importing a binary file corrupts it on the server
Type: <b>Bug</b>

Observed when testing PR #1059

1.  Be working client-side.
2.  Connect to a server namespace containing a web app with binary files (e.g. SAMPLES namespace on Cache or Ensemble).
3. Use the "CSP Files" folder of ObjectScript Explorer view to export an image file (e.g. barchartblue.jpg from the csp/samples app)
4.  Confirm that it opens correctly from your local filesystem folder (the Luna Paint image editor extension is one way of doing that inside VS Code).
5. Make a local copy of the working file, in case you subsequently overwrite the original with a bad version by re-exporting from the server after causing corruption there by importing (see below).
6. Use the Import option to send it to the server.
7. Try viewing the image file on the server filesystem. It will fail to open :bug:
8. Reinstate the file on the server filesystem by copying it from your local folder. Verify that you can now view the image on the server.

Extension version: 2.4.2-beta.5
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #1060

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
@daimor are you willing to install the dev-1064 VSIX from https://github.com/intersystems-community/vscode-objectscript/actions/runs/4060586232#artifacts so it gets some usage in a client-side paradigm context? I tested it in both paradigms, but I mostly use the server-side paradigm day to day.

**Comment by daimor** [comment]
The thing is, that for the last few month my development mostly on Python. Not a big helper here

File: src/utils/index.ts [hunk 1]
```diff
@@ -35,13 +35,20 @@ export function outputConsole(data: string[]): void {
 export interface CurrentFile {
```
[the remark this answers is not in the document]
Comment (gjsjohnmurray) [reply src/utils/index.ts:35]: I hope not. TS checks should be ensuring that places using `CurrentFile` aren't accessing the properties I moved to the subtypes.

File: src/commands/compile.ts [hunk 2]
```diff
@@ -71,23 +79,43 @@ export async function checkChangedOnServer(file: CurrentFile, force = false): Pr
...
   return api
     .putDoc(
       file.name,
       {
         content,
-        enc: false,
+        enc,
         mtime,
       },
       ignoreConflict
```
[the remark this answers is not in the document]
Comment (gjsjohnmurray) [reply src/commands/compile.ts:121]: Good point. Done.

File: src/commands/compile.ts [hunk 3]
```diff
@@ -200,7 +228,7 @@ function updateOthers(others: string[], baseUri: vscode.Uri) {
   });
```
[the remark this answers is not in the document]
Comment (gjsjohnmurray) [reply src/commands/compile.ts:230]: Done. Also improved how ObjectScript Explorer opens items that **have** been exported.

File: src/explorer/explorer.ts [hunk 4]
```diff
@@ -52,7 +52,14 @@ export function registerExplorerOpen(): vscode.Disposable {
...
 
       try {
-        await vscode.window.showTextDocument(uri, { preview: usePreview });
+        if (uri.scheme === OBJECTSCRIPT_FILE_SCHEMA) {
+          // This scheme is implemented by our DocumentContentProvider, which always returns text.
+          // If the server supplied binary data our provider substitutes a text explanation of how to work with binary content.
+          await vscode.window.showTextDocument(uri, { preview: usePreview });
+        } else {
+          //  This allows use of binary editors such as the Luna Paint extension
+          await vscode.commands.executeCommand("vscode.open", uri, { preview: usePreview });
```
Comment (isc-bsaviano) [inline src/explorer/explorer.ts:61]: I'm a little concerned about this line. Does `vscode.open` throw if `uri` can't be opened? If not then my project removal code in the catch block won't work.

File: src/commands/compile.ts [hunk 5]
```diff
@@ -413,18 +451,24 @@ export async function namespaceCompile(askFlags = false): Promise<any> {
...
             importFile(curFile).then((data) => {
               outputChannel.appendLine("Imported file: " + curFile.fileName);
               return curFile;
             })
-          )
-      )
+          );
+      })
     )
   ).then(noCompile ? Promise.resolve : compile);
```
Comment (isc-bsaviano) [inline src/commands/compile.ts:473]: One other nitpick, the extension tries to compile binary files. Should they be exempted from compilation?

File: src/explorer/explorer.ts (hunk 4 above)
Comment (gjsjohnmurray) [reply src/explorer/explorer.ts:63]: I have pushed a change for this case.

Comment (isc-bsaviano) [reply src/explorer/explorer.ts:63]: Thanks John

Comment (isc-bsaviano) [reply src/explorer/explorer.ts:63]: Actually, that doesn't fix the issue because now binary files that do exist are treated as if they don't exist. I think what we need to do is revert your last commit and before we call `vscode.open`, call `await vscode.workspace.file.stat(uri)`, which will throw `FileNotFound` if it doesn't exist.

File: src/explorer/explorer.ts [hunk 6]
```diff
@@ -52,7 +52,16 @@ export function registerExplorerOpen(): vscode.Disposable {
       }
 
       try {
-        await vscode.window.showTextDocument(uri, { preview: usePreview });
+        if (uri.scheme === OBJECTSCRIPT_FILE_SCHEMA || (project && fullName)) {
```
Comment (isc-bsaviano) [inline src/explorer/explorer.ts:55]:
```suggestion
        if (uri.scheme === OBJECTSCRIPT_FILE_SCHEMA) {
```

File: src/explorer/explorer.ts [hunk 7]
```diff
@@ -52,7 +52,16 @@ export function registerExplorerOpen(): vscode.Disposable {
...
+          // This scheme is implemented by our DocumentContentProvider, which always returns text.
+          // If the server supplied binary data our provider substitutes a text explanation of how to work with binary content.
+          //
+          // When opening from the Projects tree we also use this route because the other one (see below) doesn't throw for a missing document.
+          await vscode.window.showTextDocument(uri, { preview: usePreview });
+        } else {
+          // This allows use of binary editors such as the Luna Paint extension.
+          await vscode.commands.executeCommand("vscode.open", uri, { preview: usePreview });
```
Comment (isc-bsaviano) [inline src/explorer/explorer.ts:63]:
```suggestion
          await vscode.workspace.fs.stat(uri);
          await vscode.commands.executeCommand("vscode.open", uri, { preview: usePreview });
```

File: src/explorer/explorer.ts [hunk 8]
```diff
@@ -52,7 +52,16 @@ export function registerExplorerOpen(): vscode.Disposable {
       }
 
       try {
-        await vscode.window.showTextDocument(uri, { preview: usePreview });
+        if (uri.scheme === OBJECTSCRIPT_FILE_SCHEMA || (project && fullName)) {
+          // This scheme is implemented by our DocumentContentProvider, which always returns text.
+          // If the server supplied binary data our provider substitutes a text explanation of how to work with binary content.
+          //
```
Comment (isc-bsaviano) [inline src/explorer/explorer.ts:58]:
```suggestion
```

File: src/explorer/explorer.ts [hunk 9]
```diff
@@ -52,7 +52,16 @@ export function registerExplorerOpen(): vscode.Disposable {
...
+          // When opening from the Projects tree we also use this route because the other one (see below) doesn't throw for a missing document.
```
Comment (isc-bsaviano) [inline src/explorer/explorer.ts:59]:
```suggestion
```

File: src/commands/compile.ts (hunk 5 above)
Comment (isc-bsaviano) [reply src/commands/compile.ts:473]: @gjsjohnmurray I can implement this if you think it's worth it. If not I can approve and merge the PR.

Comment (gjsjohnmurray) [reply src/commands/compile.ts]: Pushed a change to skip them

**Review by isc-bsaviano — APPROVED** [review]
