### PR TITLE
fix issue with toUpperCase

### LINKED ISSUE #398: Choose Server and Namespace: 'Cannot read property 'toUpperCase' of undefined'
Seen in 0.9.4

Probably caused by #395

### PR DESCRIPTION
**Pull request by daimor**
This PR fixes #398

### CODE REVIEW

**Review by gjsjohnmurray — APPROVED** [review]
Thanks for the quick fix. Once merged I will release 0.9.5

File: src/api/index.ts [hunk 1]
```diff
@@ -340,16 +340,12 @@ export class AtelierAPI {
...
-   * Use the serverInfo endpoint. Connection object does not need to have specified a namespace when instantiated.
-   */
   public serverInfo(): Promise<Atelier.Response<Atelier.Content<Atelier.ServerInfo>>> {
     return this.request(0, "GET").then((info) => {
       if (info && info.result && info.result.content && info.result.content.api > 0) {
         const data = info.result.content;
         const apiVersion = data.api;
-        // If this is a namespace-specific connection, throw if it doesn't exist or if the user has no access to it
-        if (this.ns && !data.namespaces.includes(this.ns.toUpperCase())) {
+        if (!data.namespaces.includes(this.ns)) {
```
Comment (gjsjohnmurray) [inline src/api/index.ts:348]: I think this specific change has caused #400
