### PR TITLE
Log all compile error messages to Output channel

### LINKED ISSUE #1749: Compiling fails when using compile action
Are you using client-side or server-side editing?: Server-Side editing

- VS Code Version: 1.114.0
- Extension Version:  vscode-objectscript-3.8.1-beta.1.vsix
- OS: Win11
- Server `$ZVERSION` (if applicable):  "IRIS for UNIX (Red Hat Enterprise Linux 8 for x86-64) 2025.1.1 (Build 308_0_24490U) Thu Aug 28 2025 13:36:35 EDT"

when VSCode triggers a compile it seems the compile does not complete anymore at least on this environment namespace:

---snip output log---
intersystems-community.vscode-objectscript version 3.8.1-beta.1 activating with proposed APIs available.

Compilation started on 04/10/2026 11:10:46 with qualifiers 'cbk/compileembedded=1'
Compiling class redacted.cls
CheckUnique - 0
ClassValidation - 0
CreateExtract - 0
Import - 0
Compiling routine redacted.1
---

When i use light terminal and issue the same compile command it succeeds successfully:

set sc=$system.OBJ.Compile("redacted","cbk/compileembedded=1")
Compilation started on 04/10/2026 11:15:32 with qualifiers 'cbk/compileembedded=1'
Compiling class redacted
CheckUnique - 0
ClassValidation - 0
CreateExtract - 0
Import - 0
Compiling routine redacted.1
Compiling embedded SQL in 'redacted.cls'
Compilation finished successfully in 0.110s.

### PR DESCRIPTION
**Pull request by isc-bsaviano**
This PR fixes #1749. It also HTML-unescapes error strings before they are written to the Output channel so they are easier to read.

### CODE REVIEW

File: src/utils/index.ts [hunk 1]
```diff
@@ -1017,7 +1024,11 @@ export async function replaceFile(uri: vscode.Uri, content: string | string[] |
 }
 
 /** Show the compilation failure error message if required. */
-export function compileErrorMsg(): void {
+export function compileErrorMsg(error: any): void {
+  if (!(error instanceof Error && error.message.endsWith("Compile error"))) {
+    // Don't log the generic placeholder error
+    handleError(error);
```
Comment (isc-klu) [inline src/utils/index.ts]: The body of `handleError` is similar to the rest of this function. I am wondering if we want to return immediately after calling `handleError`.

Comment (isc-bsaviano) [reply src/utils/index.ts]: Yeah, this function predates `handleError()` by many years. It would probably be better to pass the message into `handleError()` then return. I'll make that change.

File: src/utils/index.ts [hunk 2]
```diff
@@ -63,16 +63,25 @@
...
+            ? <string>error.errorText
+            : typeof error == "string"
+              ? error
+              : error instanceof Error
+                ? error.toString()
+                : JSON.stringify(error)
+      )
+        .trim()
+        // Unescape any HTML-escpaed characters
+        .replaceAll("&amp;", "&")
```
[the remark this answers is not in the document]
Comment (isc-klu) [reply src/utils/index.ts]: Maybe do `&amp;` replacement last?

**Review by isc-klu — APPROVED** [review]
