### PR TITLE
Make ServerManager extension as optional, do not prevent this extension working.

### LINKED ISSUE #187: Strict extension dependency
Instead of strictly say that this extension depends on `intersystems-community.servermanager` we should offer it as an option. At the moment this extension will not work until dependency has not solved, but it could work without it anyway.

### PR DESCRIPTION
**Pull request by daimor**
resolves #187

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -253,6 +253,40 @@ export const checkConnection = (clearCookies = false): void => {
...
+      "Install",
+      "Skip",
+      "Ignore"
+    )
+    .then(async (action) => {
+      switch (action) {
+        case "Install":
+          await vscode.commands.executeCommand("workbench.extensions.installExtension", extId);
+        // eslint-disable-next-line no-fallthrough
+        case "View":
```
Comment (gjsjohnmurray) [inline src/extension.ts:277]: showInformationMessage doesn't offer "View" option

File: src/extension.ts [hunk 2]
```diff
@@ -253,6 +253,40 @@ export const checkConnection = (clearCookies = false): void => {
...
+          await vscode.commands.executeCommand("workbench.extensions.search", `@tag:"intersystems"`);
```
Comment (gjsjohnmurray) [inline src/extension.ts:278]: Why not simply search for extId?

File: src/extension.ts [hunk 3]
```diff
@@ -253,6 +253,40 @@ export const checkConnection = (clearCookies = false): void => {
...
+  const ignore =
+    config("ignoreInstallServerManager") ||
+    vscode.workspace.getConfiguration("intersystems.servers").get("/ignore", false);
+  if (ignore || vscode.extensions.getExtension(extId)) {
+    return;
+  }
+  return vscode.window
+    .showInformationMessage(
+      `Extension InterSystems® Server Manager have not installed,
+      it's recommended to install it.`,
```
Comment (gjsjohnmurray) [inline src/extension.ts:267]:
```suggestion
      "The InterSystems® Server Manager extension is recommended to help you define connections."
```

File: package.json [hunk 4]
```diff
@@ -712,6 +709,11 @@
           "type": "boolean",
           "default": false,
           "description": "Output the action that VSCode should perform as requested by the server in JSON format."
```
Comment (gjsjohnmurray) [inline package.json:711]:
```suggestion
          "description": "Output the action that VS Code should perform as requested by the server in JSON format."
```

File: package.json [hunk 5]
```diff
@@ -712,6 +709,11 @@
...
+        },
+        "objectscript.ignoreInstallServerManager": {
+          "type": "boolean",
+          "default": false,
+          "markdownDescription": "Do not offer to install `#intersystems-community.servermanager#` extension"
```
Comment (gjsjohnmurray) [inline package.json:716]: The syntax you used is only for hyperlinking to other settings.
```suggestion
          "markdownDescription": "Do not offer to install the [intersystems-community.servermanager](https://marketplace.visualstudio.com/items?itemName=intersystems-community.servermanager) helper extension."
```

**Comment by daimor** [comment]
This extension still can work without servermanager, but with extensiondependency, it does not work at all, until servermanager installed. And it’s not silently, it asks user for installation approval.

File: src/extension.ts (hunk 2 above)
Comment (daimor) [reply src/extension.ts:278]: search for extId just will show only one extension on the left panel, so, I decided to show any intersystems tagged extensions, but open particular extension in full view.

File: src/extension.ts (hunk 1 above)
Comment (daimor) [reply src/extension.ts:277]: My thoughts were, do not offer too many buttons, and was not sure if it's a good idea to install it from information message, not from extension page

Comment (gjsjohnmurray) [reply src/extension.ts:276]: In which case why is `case "View":` here?

File: src/extension.ts (hunk 2 above)
Comment (gjsjohnmurray) [reply src/extension.ts:277]: Since there's no direct path to `case "View":` the user picks "Install", the servermanager gets installed, then you show them all intersystems-tagged extensions in the list on the left, and the servermanager one displays in detail on the right. Is that what you mean? Seems a bit unexpected, but I can live with it.
